name: "hasura-sample-app"

static-env:
  STREAMING_SUBSCRIPTION_FLAG: true
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
  HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: inherited_roles
  HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"

user-env:
  PG_DB_URL:
    default: ~
    description: "Postgres database URL"
    mandatory: true
  ACTION_WEBHOOK_URL:
    default: "http://localhost:3000"
    description: "Action webhook url"
    mandatory: false
